/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2025-04-27 21:13:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Ayuda_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles/Ayuda.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("    <div class=\"logo-container\">\r\n");
      out.write("        <a href=\"Index.jsp\"><img src=\"img/bilboskp-high-resolution-logo-removebg-preview.png\"></a>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"language-selector\">\r\n");
      out.write("                <a href=\"?lang=es\" title=\"Español\">\r\n");
      out.write("                    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/1200px-Flag_of_Spain.svg.png\" alt=\"Bandera de España\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"?lang=en\" title=\"English\">\r\n");
      out.write("                    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg/1200px-Flag_of_the_United_Kingdom_%283-5%29.svg.png\" alt=\"Bandera del Reino Unido\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    <nav>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"EscapeRooms.jsp\">Jugar</a>\r\n");
      out.write("        <a href=\"OrganizarPartida.jsp\">Organizar Partida</a>\r\n");
      out.write("        <a href=\"Packcupones.jsp\">Comprar cupones</a>\r\n");
      out.write("        <a href=\"DevolverCupones.jsp\">Devolver cupones</a>\r\n");
      out.write("        <a href=\"QuienesSomos.jsp\">Quiénes Somos</a>\r\n");
      out.write("        <a href=\"Ayuda.jsp\">Ayuda</a>\r\n");
      out.write("\r\n");
      out.write("        ");

            Integer idRolUsuario = (Integer) request.getAttribute("idRol");
            Integer idCentroSesion = (Integer) request.getAttribute("idCentroSesion");

            // Mostrar "Registrar Centro" solo si el usuario no está logueado como centro
            if (idCentroSesion == null && idRolUsuario != null && idRolUsuario.equals(2)) {
        
      out.write("\r\n");
      out.write("                <a href=\"CentroRegistro.jsp\">Registrar Centro</a>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"botones\">\r\n");
      out.write("    ");

        String nombreSesion = (String) request.getAttribute("nombreSesion");
        String tipoUsuario = (String) request.getAttribute("tipoUsuario");
        Integer saldoCupones = (Integer) request.getAttribute("saldoCupones");

        if (nombreSesion != null && !nombreSesion.isEmpty()) {
            if (tipoUsuario != null && tipoUsuario.equals("usuario")) {
    
      out.write("\r\n");
      out.write("                <span class=\"nombre-usuario\">Bienvenido, ");
      out.print( nombreSesion );
      out.write(' ');
      out.write('(');
      out.print( saldoCupones != null ? saldoCupones : 0 );
      out.write(" cupones)</span>\r\n");
      out.write("                <button onclick=\"window.location.href='LogoutServlet'\">Cerrar Sesión</button>\r\n");
      out.write("    ");

            } else if (tipoUsuario != null && tipoUsuario.equals("centro")) {
    
      out.write("\r\n");
      out.write("                <span class=\"nombre-centro\">Bienvenido, ");
      out.print( nombreSesion );
      out.write(' ');
      out.write('(');
      out.print( saldoCupones != null ? saldoCupones : 0 );
      out.write(" cupones)</span>\r\n");
      out.write("                <button onclick=\"window.location.href='LogoutCentroServlet'\">Cerrar Sesión</button>\r\n");
      out.write("    ");

            }
        } else {
    
      out.write("\r\n");
      out.write("        <button class= \"registrarse\" onclick=\"window.location.href='Registrar.jsp'\">Registrarse</button>\r\n");
      out.write("        <button onclick=\"window.location.href='login.jsp'\">Iniciar Sesion</button>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <section class=\"hero\">\r\n");
      out.write("        <div class=\"hero-content\">\r\n");
      out.write("            <h1>Centro de Ayuda para Salas de Escape Online</h1>\r\n");
      out.write("            <p>Encuentra respuestas a todas tus preguntas sobre nuestras salas de escape virtuales</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <main class=\"containera\">\r\n");
      out.write("        <!-- Getting Started Section -->\r\n");
      out.write("        <section class=\"help-section\">\r\n");
      out.write("            <h2 class=\"section-title\">Primeros Pasos</h2>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"cards-container\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-img\">\r\n");
      out.write("                        <img src=\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%233498db' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><circle cx='12' cy='12' r='10'/><path d='M8 14s1.5 2 4 2 4-2 4-2'/><line x1='9' y1='9' x2='9.01' y2='9'/><line x1='15' y1='9' x2='15.01' y2='9'/></svg>\" alt=\"Cómo Funciona\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("                        <h3>Cómo Funcionan las Salas Online</h3>\r\n");
      out.write("                        <p>Descubre cómo funcionan nuestras salas de escape virtuales y cómo puedes disfrutar de la experiencia desde casa.</p>\r\n");
      out.write("                        <a href=\"mailto:skpbilbo@gmail.com\" class=\"btn btn-outline\">Preguntanos</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-img\">\r\n");
      out.write("                        <img src=\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%233498db' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2'/><circle cx='9' cy='7' r='4'/><path d='M23 21v-2a4 4 0 0 0-3-3.87'/><path d='M16 3.13a4 4 0 0 1 0 7.75'/></svg>\" alt=\"Crear Equipo\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("                        <h3>Crear y Unirse a un Equipo</h3>\r\n");
      out.write("                        <p>Aprende a crear un equipo e invitar a tus amigos para jugar juntos en nuestras salas de escape virtuales.</p>\r\n");
      out.write("                        <a href=\"mailto:skpbilbo@gmail.com\" class=\"btn btn-outline\">Preguntanos</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-img\">\r\n");
      out.write("                        <img src=\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%233498db' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='2' y='3' width='20' height='14' rx='2' ry='2'/><line x1='8' y1='21' x2='16' y2='21'/><line x1='12' y1='17' x2='12' y2='21'/></svg>\" alt=\"Requisitos Técnicos\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("                        <h3>Requisitos Técnicos</h3>\r\n");
      out.write("                        <p>Conoce los requisitos técnicos necesarios para disfrutar de la mejor experiencia en nuestras salas virtuales.</p>\r\n");
      out.write("                        <a href=\"mailto:skpbilbo@gmail.com\" class=\"btn btn-outline\">Preguntanos</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Tips and Tricks Section -->\r\n");
      out.write("        <section class=\"help-section\">\r\n");
      out.write("            <h2 class=\"section-title\">Consejos y Trucos</h2>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"cards-container\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-img\">\r\n");
      out.write("                        <img src=\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%233498db' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><polygon points='12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2'/></svg>\" alt=\"Mejores Prácticas\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("                        <h3>Mejores Prácticas</h3>\r\n");
      out.write("                        <p>Consejos para mejorar tu experiencia y aumentar tus posibilidades de escapar con éxito.</p>\r\n");
      out.write("                        <a href=\"mailto:skpbilbo@gmail.com\" class=\"btn btn-outline\">Preguntanos</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-img\">\r\n");
      out.write("                        <img src=\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%233498db' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3'/></svg>\" alt=\"Comunicación Efectiva\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("                        <h3>Comunicación Efectiva</h3>\r\n");
      out.write("                        <p>Aprende a comunicarte eficazmente con tu equipo durante la experiencia de escape virtual.</p>\r\n");
      out.write("                      	<a href=\"mailto:skpbilbo@gmail.com\" class=\"btn btn-outline\">Preguntanos</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-img\">\r\n");
      out.write("                        <img src=\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%233498db' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><circle cx='12' cy='12' r='10'/><line x1='12' y1='8' x2='12' y2='12'/><line x1='12' y1='16' x2='12.01' y2='16'/></svg>\" alt=\"Errores Comunes\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("                        <h3>Errores Comunes a Evitar</h3>\r\n");
      out.write("                        <p>Conoce los errores más comunes que cometen los jugadores y cómo evitarlos para mejorar tu experiencia.</p>\r\n");
      out.write("                        <a href=\"mailto:skpbilbo@gmail.com\" class=\"btn btn-outline\">Preguntanos</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("        <!-- FAQ Section -->\r\n");
      out.write("        <section class=\"help-section\">\r\n");
      out.write("            <h2 class=\"section-title\">Preguntas Frecuentes</h2>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"faq-container\">\r\n");
      out.write("                <div class=\"faq-item\">\r\n");
      out.write("                    <div class=\"faq-question\">¿Cómo puedo reservar una sala de escape online?</div>\r\n");
      out.write("                    <div class=\"faq-answer\">Para reservar una sala de escape online, simplemente navega a la sección \"Jugar\" en nuestro sitio web, selecciona la sala que te interese y teniendo saldo de cupones podrá acceder a nuestra salas de escape virtuales.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"faq-item\">\r\n");
      out.write("                    <div class=\"faq-question\">¿Cuántas personas pueden participar en una sala virtual?</div>\r\n");
      out.write("                    <div class=\"faq-answer\">El número de participantes varía según la sala, pero generalmente nuestras salas virtuales están diseñadas para equipos de 2 a 6 jugadores.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"faq-item\">\r\n");
      out.write("                    <div class=\"faq-question\">¿Qué sucede si tengo problemas técnicos durante el juego?</div>\r\n");
      out.write("                    <div class=\"faq-answer\">Si experimentas problemas técnicos durante el juego, puedes mandarnos un correo y te atenderemos lo antes posible.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"faq-item\">\r\n");
      out.write("                    <div class=\"faq-question\">¿Necesito descargar algún software especial?</div>\r\n");
      out.write("                    <div class=\"faq-answer\">Si es necesario descargar el software de cada sala de escape para participar en nuestras salas de escape virtuales. Sin embargo, recomendamos utilizar una conexión a Internet estable.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"faq-item\">\r\n");
      out.write("                    <div class=\"faq-question\">¿Puedo solicitar pistas durante el juego?</div>\r\n");
      out.write("                    <div class=\"faq-answer\">¡Sí! Todas nuestras salas de escape virtuales incluyen un sistema de pistas. Si se queda atascado, pueden solicitar pistas.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>BilboSKP</h3>\r\n");
      out.write("                    <p>La mejor plataforma de escape rooms en Bilbao. Vive la aventura con nosotros.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>Enlaces</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"Index.jsp\">Inicio</a></li>\r\n");
      out.write("                        <li><a href=\"QuienesSomos.jsp\">Quiénes Somos</a></li>\r\n");
      out.write("                        <li><a href=\"EscapeRooms.jsp\">Salas de Escape</a></li>\r\n");
      out.write("                        <li><a href=\"Ayuda.jsp\">Ayuda</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>Contacto</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>Email: skpbilbo@gmail.com</li>\r\n");
      out.write("                        <li>Dirección: Calle Principal 123, Bilbao</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-bottom\">\r\n");
      out.write("                <p>&copy; 2025 BilboSKP. Todos los derechos reservados.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
