/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2025-04-27 22:18:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class EditarPartida_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles/EditarPartida.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <title>Editar partida</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"logo-container\">\r\n");
      out.write("        <a href=\"Index.jsp\"><img src=\"img/bilboskp-high-resolution-logo-removebg-preview.png\"></a>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"language-selector\">\r\n");
      out.write("                <a href=\"?lang=es\" title=\"Español\">\r\n");
      out.write("                    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/1200px-Flag_of_Spain.svg.png\" alt=\"Bandera de España\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"?lang=en\" title=\"English\">\r\n");
      out.write("                    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg/1200px-Flag_of_the_United_Kingdom_%283-5%29.svg.png\" alt=\"Bandera del Reino Unido\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    <nav>\r\n");
      out.write("        <a href=\"EscapeRooms.jsp\">Jugar</a>\r\n");
      out.write("        <a href=\"OrganizarPartida.jsp\">Organizar Partida</a>\r\n");
      out.write("        ");

            String tipoUsuarioNav = (String) request.getAttribute("tipoUsuario");
            if (tipoUsuarioNav != null && tipoUsuarioNav.equals("centro")) {
        
      out.write("\r\n");
      out.write("            <a href=\"SolicitarCupones.jsp\">Solicitar cupones</a>\r\n");
      out.write("        ");

            } else {
        
      out.write("\r\n");
      out.write("            <a href=\"Packcupones.jsp\">Comprar cupones</a>\r\n");
      out.write("            <a href=\"DevolverCupones.jsp\">Devolver cupones</a>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("        <a href=\"QuienesSomos.jsp\">Quiénes Somos</a>\r\n");
      out.write("        <a href=\"Ayuda.jsp\">Ayuda</a>\r\n");
      out.write("\r\n");
      out.write("        ");

            Integer idRolUsuarioNav = (Integer) request.getAttribute("idRol");
            Integer idCentroSesionNav = (Integer) request.getAttribute("idCentroSesion");

            // Mostrar "Registrar Centro" solo si el usuario no está logueado como centro y es un administrador (idRol 2)
            if (idCentroSesionNav == null && idRolUsuarioNav != null && idRolUsuarioNav.equals(2)) {
        
      out.write("\r\n");
      out.write("            <a href=\"CentroRegistro.jsp\">Registrar Centro</a>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"botones\">\r\n");
      out.write("    ");

        String nombreSesion = (String) request.getAttribute("nombreSesion");
        String tipoUsuario = (String) request.getAttribute("tipoUsuario");
        Integer saldoCupones = (Integer) request.getAttribute("saldoCupones");

        if (nombreSesion != null && !nombreSesion.isEmpty()) {
            if (tipoUsuario != null && tipoUsuario.equals("usuario")) {
    
      out.write("\r\n");
      out.write("                <span class=\"nombre-usuario\">Bienvenido, ");
      out.print( nombreSesion );
      out.write(' ');
      out.write('(');
      out.print( saldoCupones != null ? saldoCupones : 0 );
      out.write(" cupones)</span>\r\n");
      out.write("                <button onclick=\"window.location.href='LogoutServlet'\">Cerrar Sesión</button>\r\n");
      out.write("    ");

            } else if (tipoUsuario != null && tipoUsuario.equals("centro")) {
    
      out.write("\r\n");
      out.write("                <span class=\"nombre-centro\">Bienvenido, ");
      out.print( nombreSesion );
      out.write(' ');
      out.write('(');
      out.print( saldoCupones != null ? saldoCupones : 0 );
      out.write(" cupones)</span>\r\n");
      out.write("                <button onclick=\"window.location.href='LogoutCentroServlet'\">Cerrar Sesión</button>\r\n");
      out.write("    ");

            }
        } else {
    
      out.write("\r\n");
      out.write("        <button class= \"registrarse\" onclick=\"window.location.href='Registrar.jsp'\">Registrarse</button>\r\n");
      out.write("        <button onclick=\"window.location.href='login.jsp'\">Iniciar Sesion</button>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <main>\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("      <div class=\"card-header\">\r\n");
      out.write("        <div class=\"dots\">\r\n");
      out.write("          <span class=\"dot\"></span>\r\n");
      out.write("          <span class=\"dot\"></span>\r\n");
      out.write("          <span class=\"dot\"></span>\r\n");
      out.write("          <span class=\"dot\"></span>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"OrganizarPartida.jsp\" class=\"back-link\">\r\n");
      out.write("          <svg class=\"icon\" viewBox=\"0 0 24 24\">\r\n");
      out.write("            <line x1=\"19\" y1=\"12\" x2=\"5\" y2=\"12\"></line>\r\n");
      out.write("            <polyline points=\"12 19 5 12 12 5\"></polyline>\r\n");
      out.write("          </svg>\r\n");
      out.write("          Volver a partidas\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <h1 class=\"card-title\">Editar partida</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"form-container\">\r\n");
      out.write("        <form id=\"editar-partida-form\">\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <label for=\"nombre\">Nombre de la partida</label>\r\n");
      out.write("            <input type=\"text\" id=\"nombre\" value=\"Torneo de Verano 2023\">\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <label for=\"numJugadores\">Número de jugadores: <span id=\"jugadores-valor\">16</span></label>\r\n");
      out.write("            <div class=\"slider-container\">\r\n");
      out.write("              <input type=\"range\" id=\"numJugadores\" class=\"slider\" min=\"2\" max=\"200\" value=\"16\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"slider-value\">\r\n");
      out.write("              <svg class=\"icon\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                <path d=\"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2\"></path>\r\n");
      out.write("                <circle cx=\"9\" cy=\"7\" r=\"4\"></circle>\r\n");
      out.write("                <path d=\"M23 21v-2a4 4 0 0 0-3-3.87\"></path>\r\n");
      out.write("                <path d=\"M16 3.13a4 4 0 0 1 0 7.75\"></path>\r\n");
      out.write("              </svg>\r\n");
      out.write("              <span id=\"jugadores-valor-icon\">16</span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"grid-2\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"fecha\">Fecha de caducidad</label>\r\n");
      out.write("              <div class=\"input-with-icon\">\r\n");
      out.write("                <svg class=\"icon input-icon\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                  <rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\" ry=\"2\"></rect>\r\n");
      out.write("                  <line x1=\"16\" y1=\"2\" x2=\"16\" y2=\"6\"></line>\r\n");
      out.write("                  <line x1=\"8\" y1=\"2\" x2=\"8\" y2=\"6\"></line>\r\n");
      out.write("                  <line x1=\"3\" y1=\"10\" x2=\"21\" y2=\"10\"></line>\r\n");
      out.write("                </svg>\r\n");
      out.write("                <input type=\"date\" id=\"fecha\" value=\"2023-08-30\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"hora\">Hora de caducidad</label>\r\n");
      out.write("              <div class=\"input-with-icon\">\r\n");
      out.write("                <svg class=\"icon input-icon\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                  <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                  <polyline points=\"12 6 12 12 16 14\"></polyline>\r\n");
      out.write("                </svg>\r\n");
      out.write("                <input type=\"time\" id=\"hora\" value=\"18:00\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <label for=\"tipo\">Tipo de partida</label>\r\n");
      out.write("            <select id=\"tipo\">\r\n");
      out.write("              <option value=\"casual\">Casual</option>\r\n");
      out.write("              <option value=\"competitiva\" selected>Competitiva</option>\r\n");
      out.write("              <option value=\"amistosa\">Amistosa</option>\r\n");
      out.write("              <option value=\"torneo\">Torneo</option>\r\n");
      out.write("            </select>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <label for=\"descripcion\">Descripción (opcional)</label>\r\n");
      out.write("            <textarea id=\"descripcion\"></textarea>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"info-section\">\r\n");
      out.write("            <h3 class=\"info-title\">Información adicional</h3>\r\n");
      out.write("            <div class=\"info-grid\">\r\n");
      out.write("              <div class=\"info-item\">\r\n");
      out.write("                <div class=\"info-label\">Fecha de creación</div>\r\n");
      out.write("                <div class=\"info-value\">15/06/2023</div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"info-item\">\r\n");
      out.write("                <div class=\"info-label\">Creado por</div>\r\n");
      out.write("                <div class=\"info-value\">admin@bilboskp.com</div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"info-item\">\r\n");
      out.write("                <div class=\"info-label\">Última modificación</div>\r\n");
      out.write("                <div class=\"info-value\">20/06/2023</div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"info-item\">\r\n");
      out.write("                <div class=\"info-label\">Estado</div>\r\n");
      out.write("                <div class=\"info-value\">Activo</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"button-container\">\r\n");
      out.write("            <button type=\"button\" class=\"secondary-button\" id=\"cancelar-btn\">Cancelar</button>\r\n");
      out.write("            <button type=\"submit\" class=\"primary-button\">Guardar cambios</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"button-container\" style=\"margin-top: 12px;\">\r\n");
      out.write("            <button type=\"button\" class=\"danger-button\" id=\"eliminar-btn\">Eliminar partida</button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </main>\r\n");
      out.write("  \r\n");
      out.write("  <footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>BilboSKP</h3>\r\n");
      out.write("                    <p>La mejor plataforma de escape rooms en Bilbao. Vive la aventura con nosotros.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>Enlaces</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"Index.jsp\">Inicio</a></li>\r\n");
      out.write("                        <li><a href=\"QuienesSomos.jsp\">Quiénes Somos</a></li>\r\n");
      out.write("                        <li><a href=\"EscapeRooms.jsp\">Salas de Escape</a></li>\r\n");
      out.write("                        <li><a href=\"Ayuda.jsp\">Ayuda</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>Contacto</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>Email: skpbilbo@gmail.com</li>\r\n");
      out.write("                        <li>Dirección: Calle Principal 123, Bilbao</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-bottom\">\r\n");
      out.write("                <p>&copy; 2025 BilboSKP. Todos los derechos reservados.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("    // Script para actualizar el valor del slider\r\n");
      out.write("    const sliderElement = document.getElementById('numJugadores');\r\n");
      out.write("    const jugadoresValor = document.getElementById('jugadores-valor');\r\n");
      out.write("    const jugadoresValorIcon = document.getElementById('jugadores-valor-icon');\r\n");
      out.write("    \r\n");
      out.write("    sliderElement.addEventListener('input', function() {\r\n");
      out.write("      const value = this.value;\r\n");
      out.write("      jugadoresValor.textContent = value;\r\n");
      out.write("      jugadoresValorIcon.textContent = value;\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    // Prevenir envío del formulario (para demostración)\r\n");
      out.write("    document.getElementById('editar-partida-form').addEventListener('submit', function(e) {\r\n");
      out.write("      e.preventDefault();\r\n");
      out.write("      alert('Cambios guardados (demostración)');\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    // Botón cancelar\r\n");
      out.write("    document.getElementById('cancelar-btn').addEventListener('click', function() {\r\n");
      out.write("      if (confirm('¿Estás seguro de que quieres cancelar la edición? Los cambios no guardados se perderán.')) {\r\n");
      out.write("        // Redirigir a la página de partidas (para demostración)\r\n");
      out.write("        alert('Edición cancelada (demostración)');\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    // Botón eliminar\r\n");
      out.write("    document.getElementById('eliminar-btn').addEventListener('click', function() {\r\n");
      out.write("      if (confirm('¿Estás seguro de que quieres eliminar esta partida? Esta acción no se puede deshacer.')) {\r\n");
      out.write("        // Eliminar partida (para demostración)\r\n");
      out.write("        alert('Partida eliminada (demostración)');\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
