/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2025-04-27 22:25:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class QuienesSomos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles/QuienesSomos.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"logo-container\">\r\n");
      out.write("        <a href=\"Index.jsp\"><img src=\"img/bilboskp-high-resolution-logo-removebg-preview.png\"></a>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"language-selector\">\r\n");
      out.write("                <a href=\"?lang=es\" title=\"Español\">\r\n");
      out.write("                    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/1200px-Flag_of_Spain.svg.png\" alt=\"Bandera de España\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"?lang=en\" title=\"English\">\r\n");
      out.write("                    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg/1200px-Flag_of_the_United_Kingdom_%283-5%29.svg.png\" alt=\"Bandera del Reino Unido\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    <nav>\r\n");
      out.write("        <a href=\"EscapeRooms.jsp\">Jugar</a>\r\n");
      out.write("        <a href=\"OrganizarPartida.jsp\">Organizar Partida</a>\r\n");
      out.write("        ");

            String tipoUsuarioNav = (String) request.getAttribute("tipoUsuario");
            if (tipoUsuarioNav != null && tipoUsuarioNav.equals("centro")) {
        
      out.write("\r\n");
      out.write("            <a href=\"SolicitarCupones.jsp\">Solicitar cupones</a>\r\n");
      out.write("        ");

            } else {
        
      out.write("\r\n");
      out.write("            <a href=\"Packcupones.jsp\">Comprar cupones</a>\r\n");
      out.write("            <a href=\"DevolverCupones.jsp\">Devolver cupones</a>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("        <a href=\"QuienesSomos.jsp\">Quiénes Somos</a>\r\n");
      out.write("        <a href=\"Ayuda.jsp\">Ayuda</a>\r\n");
      out.write("\r\n");
      out.write("        ");

            Integer idRolUsuarioNav = (Integer) request.getAttribute("idRol");
            Integer idCentroSesionNav = (Integer) request.getAttribute("idCentroSesion");

            // Mostrar "Registrar Centro" solo si el usuario no está logueado como centro y es un administrador (idRol 2)
            if (idCentroSesionNav == null && idRolUsuarioNav != null && idRolUsuarioNav.equals(2)) {
        
      out.write("\r\n");
      out.write("            <a href=\"CentroRegistro.jsp\">Registrar Centro</a>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"botones\">\r\n");
      out.write("    ");

        String nombreSesion = (String) request.getAttribute("nombreSesion");
        String tipoUsuario = (String) request.getAttribute("tipoUsuario");
        Integer saldoCupones = (Integer) request.getAttribute("saldoCupones");

        if (nombreSesion != null && !nombreSesion.isEmpty()) {
            if (tipoUsuario != null && tipoUsuario.equals("usuario")) {
    
      out.write("\r\n");
      out.write("                <span class=\"nombre-usuario\">Bienvenido, ");
      out.print( nombreSesion );
      out.write(' ');
      out.write('(');
      out.print( saldoCupones != null ? saldoCupones : 0 );
      out.write(" cupones)</span>\r\n");
      out.write("                <button onclick=\"window.location.href='LogoutServlet'\">Cerrar Sesión</button>\r\n");
      out.write("    ");

            } else if (tipoUsuario != null && tipoUsuario.equals("centro")) {
    
      out.write("\r\n");
      out.write("                <span class=\"nombre-centro\">Bienvenido, ");
      out.print( nombreSesion );
      out.write(' ');
      out.write('(');
      out.print( saldoCupones != null ? saldoCupones : 0 );
      out.write(" cupones)</span>\r\n");
      out.write("                <button onclick=\"window.location.href='LogoutCentroServlet'\">Cerrar Sesión</button>\r\n");
      out.write("    ");

            }
        } else {
    
      out.write("\r\n");
      out.write("        <button class= \"registrarse\" onclick=\"window.location.href='Registrar.jsp'\">Registrarse</button>\r\n");
      out.write("        <button onclick=\"window.location.href='login.jsp'\">Iniciar Sesion</button>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <main>\r\n");
      out.write("        <section class=\"hero\">\r\n");
      out.write("            <div class=\"containerq\">\r\n");
      out.write("                <h2>Quiénes Somos</h2>\r\n");
      out.write("                <p class=\"subtitle\">Descubre la historia detrás de BilboSKP</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"about-section\">\r\n");
      out.write("            <div class=\"containerq\">\r\n");
      out.write("                <div class=\"about-block\">\r\n");
      out.write("                    <h3>Nuestra Historia</h3>\r\n");
      out.write("                    <p>BilboSKP nació en 2015 en el corazón de Bilbao con una misión clara: transformar el concepto de ocio y entretenimiento a través de experiencias inmersivas únicas. Fundada por un grupo de entusiastas de los juegos de ingenio y las aventuras, nuestra empresa ha crecido hasta convertirse en un referente de los escape rooms en el País Vasco.</p>\r\n");
      out.write("                    \r\n");
      out.write("                    <p>Lo que comenzó como una pequeña sala en el Casco Viejo de Bilbao se ha expandido a múltiples ubicaciones, manteniendo siempre nuestra sede central en la ciudad que nos vio nacer.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"about-block\">\r\n");
      out.write("                    <h3>Nuestra Misión</h3>\r\n");
      out.write("                    <p>En BilboSKP creemos que el entretenimiento puede ser mucho más que pasar el tiempo. Buscamos crear experiencias memorables que fomenten el trabajo en equipo, la resolución de problemas y la creatividad, todo mientras nuestros participantes se sumergen en historias fascinantes.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"about-image-section\">\r\n");
      out.write("            <div class=\"containerq\">\r\n");
      out.write("                <img src=\"img/Gemini8.jpg?height=400&width=800\" alt=\"Oficina central de BilboSKP en Bilbao\" class=\"rounded-image\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"values-section\">\r\n");
      out.write("            <div class=\"containerq\">\r\n");
      out.write("                <h3 class=\"section-title\">Nuestros Valores</h3>\r\n");
      out.write("                <div class=\"values-grid\">\r\n");
      out.write("                    <div class=\"value-card\">\r\n");
      out.write("                        <div class=\"value-icon\">🧩</div>\r\n");
      out.write("                        <h4>Innovación</h4>\r\n");
      out.write("                        <p>Constantemente desarrollamos nuevos enigmas y tecnologías para ofrecer experiencias únicas.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"value-card\">\r\n");
      out.write("                        <div class=\"value-icon\">🤝</div>\r\n");
      out.write("                        <h4>Trabajo en equipo</h4>\r\n");
      out.write("                        <p>Creemos en el poder de la colaboración para superar desafíos y crear momentos inolvidables.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"value-card\">\r\n");
      out.write("                        <div class=\"value-icon\">🌍</div>\r\n");
      out.write("                        <h4>Sostenibilidad</h4>\r\n");
      out.write("                        <p>Nos comprometemos con prácticas responsables con el medio ambiente en todas nuestras operaciones.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"value-card\">\r\n");
      out.write("                        <div class=\"value-icon\">🔍</div>\r\n");
      out.write("                        <h4>Calidad</h4>\r\n");
      out.write("                        <p>Cuidamos cada detalle para garantizar la mejor experiencia posible a nuestros visitantes.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"team-section\">\r\n");
      out.write("            <div class=\"containerq\">\r\n");
      out.write("                <h3 class=\"section-title\">Nuestro Equipo</h3>\r\n");
      out.write("                <p class=\"section-subtitle\">Conoce a las mentes creativas detrás de BilboSKP</p>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"team-grid\">\r\n");
      out.write("                    <div class=\"team-member\">\r\n");
      out.write("                        <div class=\"member-image\">\r\n");
      out.write("                            <img src=\"img/NPC1.png\" height=\"100\" width=\"100\" alt=\"Mikel Etxebarria - Fundador y Director\" class=\"rounded-image\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4>Mikel Etxebarria</h4>\r\n");
      out.write("                        <p class=\"member-role\">Fundador y Director</p>\r\n");
      out.write("                        <p>Apasionado de los enigmas y con experiencia en diseño de juegos, Mikel fundó BilboSKP con la visión de crear experiencias inmersivas únicas.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"team-member\">\r\n");
      out.write("                        <div class=\"member-image\">\r\n");
      out.write("                            <img src=\"img/NPC2.png\" height=\"200\" width=\"200\" alt=\"Ane Zubieta - Directora Creativa\" class=\"rounded-image\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4>Ane Zubieta</h4>\r\n");
      out.write("                        <p class=\"member-role\">Directora Creativa</p>\r\n");
      out.write("                        <p>Con formación en bellas artes y narrativa, Ane es la mente detrás de las historias y ambientaciones que dan vida a nuestros escape rooms.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"team-member\">\r\n");
      out.write("                        <div class=\"member-image\">\r\n");
      out.write("                            <img src=\"img/NPC3.png\" height=\"200\" width=\"200\" alt=\"Jon Urrutia - Director Técnico\" class=\"rounded-image\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4>Jon Urrutia</h4>\r\n");
      out.write("                        <p class=\"member-role\">Director Técnico</p>\r\n");
      out.write("                        <p>Ingeniero electrónico especializado en sistemas interactivos, Jon desarrolla los mecanismos y tecnologías que hacen posibles nuestros desafíos.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"location-section\">\r\n");
      out.write("            <div class=\"containerq\">\r\n");
      out.write("                <h3 class=\"section-title\">Nuestra Sede Central</h3>\r\n");
      out.write("                <div class=\"location-grid\">\r\n");
      out.write("                    <div class=\"location-map\">\r\n");
      out.write("                        <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d23247.63280585631!2d-2.9400369999999997!3d43.2630126!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd4e4e27664b89b9%3A0x6534acc41e95a645!2sBilbao%2C%20Vizcaya!5e0!3m2!1ses!2ses!4v1649252594777!5m2!1ses!2ses\" width=\"100%\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"location-info\">\r\n");
      out.write("                        <h4>BilboSKP - Oficina Central</h4>\r\n");
      out.write("                        <p><strong>Dirección:</strong> Calle Alameda de Mazarredo, 65, 48009 Bilbao, Vizcaya</p>\r\n");
      out.write("                        <p><strong>Email:</strong> skpbilbo@gmail.com</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"cta-section\">\r\n");
      out.write("            <div class=\"containerq\">\r\n");
      out.write("                <h3>¿Listo para la aventura?</h3>\r\n");
      out.write("                <p>Descubre nuestros escape rooms y vive una experiencia inolvidable</p>\r\n");
      out.write("                <a href=\"EscapeRooms.jsp\" class=\"btn btn-primary btn-large\">Ver Escape Rooms</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>BilboSKP</h3>\r\n");
      out.write("                    <p>La mejor plataforma de escape rooms en Bilbao. Vive la aventura con nosotros.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>Enlaces</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"Index.jsp\">Inicio</a></li>\r\n");
      out.write("                        <li><a href=\"QuienesSomos.jsp\">Quiénes Somos</a></li>\r\n");
      out.write("                        <li><a href=\"EscapeRooms.jsp\">Salas de Escape</a></li>\r\n");
      out.write("                        <li><a href=\"Ayuda.jsp\">Ayuda</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>Contacto</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>Email: skpbilbo@gmail.com</li>\r\n");
      out.write("                        <li>Dirección: Calle Principal 123, Bilbao</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-bottom\">\r\n");
      out.write("                <p>&copy; 2025 BilboSKP. Todos los derechos reservados.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
