/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2025-04-27 18:09:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Registrar3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Registro de Usuario</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles/RegistroUser.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"logo-container\">\r\n");
      out.write("        <a href=\"Index.jsp\"><img src=\"img/bilboskp-high-resolution-logo-removebg-preview.png\"></a>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"language-selector\">\r\n");
      out.write("                <a href=\"?lang=es\" title=\"Español\">\r\n");
      out.write("                    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/1200px-Flag_of_Spain.svg.png\" alt=\"Bandera de España\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"?lang=en\" title=\"English\">\r\n");
      out.write("                    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg/1200px-Flag_of_the_United_Kingdom_%283-5%29.svg.png\" alt=\"Bandera del Reino Unido\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    <nav>\r\n");
      out.write("    \r\n");
      out.write("        <a href=\"EscapeRooms.jsp\">Jugar</a>\r\n");
      out.write("        <a href=\"OrganizarPartida.jsp\">Organizar Partida</a>\r\n");
      out.write("        <a href=\"Packcupones.jsp\">Comprar cupones</a>\r\n");
      out.write("		<a href=\"DevolverCupones.jsp\">Devolver cupones</a>\r\n");
      out.write("        <a href=\"QuienesSomos.jsp\">Quiénes Somos</a>\r\n");
      out.write("        <a href=\"Ayuda.jsp\">Ayuda</a>\r\n");
      out.write("        \r\n");
      out.write("        ");

            Integer idRolUsuario = (Integer) request.getAttribute("idRol");
            Integer idCentroSesion = (Integer) request.getAttribute("idCentroSesion");

            // Mostrar "Registrar Centro" solo si el usuario no está logueado como centro
            if (idCentroSesion == null && idRolUsuario != null && idRolUsuario.equals(2)) {
        
      out.write("\r\n");
      out.write("                <a href=\"CentroRegistro.jsp\">Registrar Centro</a>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"botones\">\r\n");
      out.write("    ");

        String nombreSesion = (String) request.getAttribute("nombreSesion");
        String tipoUsuario = (String) request.getAttribute("tipoUsuario");
        Integer saldoCupones = (Integer) request.getAttribute("saldoCupones");

        if (nombreSesion != null && !nombreSesion.isEmpty()) {
            if (tipoUsuario != null && tipoUsuario.equals("usuario")) {
    
      out.write("\r\n");
      out.write("                <span class=\"nombre-usuario\">Bienvenido, ");
      out.print( nombreSesion );
      out.write(' ');
      out.write('(');
      out.print( saldoCupones != null ? saldoCupones : 0 );
      out.write(" cupones)</span>\r\n");
      out.write("                <button onclick=\"window.location.href='LogoutServlet'\">Cerrar Sesión</button>\r\n");
      out.write("    ");

            } else if (tipoUsuario != null && tipoUsuario.equals("centro")) {
    
      out.write("\r\n");
      out.write("                <span class=\"nombre-centro\">Bienvenido, ");
      out.print( nombreSesion );
      out.write("</span>\r\n");
      out.write("                <button onclick=\"window.location.href='LogoutCentroServlet'\">Cerrar Sesión</button>\r\n");
      out.write("    ");

            }
        } else {
    
      out.write("\r\n");
      out.write("        <button class= \"registrarse\" onclick=\"window.location.href='Registrar.jsp'\">Registrarse</button>\r\n");
      out.write("        <button onclick=\"window.location.href='login.jsp'\">Iniciar Sesion</button>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <main>\r\n");
      out.write("        <div class=\"background-pattern\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"containerR\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("            <a href=\"Registrar.jsp\" class=\"back-link\">\r\n");
      out.write("          <svg class=\"icon\" viewBox=\"0 0 24 24\">\r\n");
      out.write("            <line x1=\"19\" y1=\"12\" x2=\"5\" y2=\"12\"></line>\r\n");
      out.write("            <polyline points=\"12 19 5 12 12 5\"></polyline>\r\n");
      out.write("          </svg>\r\n");
      out.write("          Volver al menu\r\n");
      out.write("        </a>\r\n");
      out.write("                <div class=\"card-header\">\r\n");
      out.write("                    <h1>Suscríbete a BilboSKP</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"subscription-highlight\">\r\n");
      out.write("                    <div class=\"plan-badge\">Plan Estandar</div>\r\n");
      out.write("                    <div class=\"plan-price\">\r\n");
      out.write("                        <span class=\"price\">15$</span>\r\n");
      out.write("                        <span class=\"period\">/mes</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"plan-features\">\r\n");
      out.write("                        <li>Opción de compra de tickets de juego</li>\r\n");
      out.write("                        <li>Soporte humano</li>\r\n");
      out.write("                        <li>Cancela cuando quieras</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"progress-bar\">\r\n");
      out.write("                    <div class=\"progress-steps\">\r\n");
      out.write("                        <div class=\"step active completed\">\r\n");
      out.write("                            <div class=\"step-number\">1</div>\r\n");
      out.write("                            <div class=\"step-line\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"step active\">\r\n");
      out.write("                            <div class=\"step-number\">2</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"progress-labels\">\r\n");
      out.write("                        <span class=\"active\">Datos personales</span>\r\n");
      out.write("                        <span class=\"active\">Método de pago</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <form id=\"registration-form\" action=\"guardarUsuario\" method=\"post\">\r\n");
      out.write("                    <div class=\"step-content\" id=\"step1\">\r\n");
      out.write("                        <h2>Información personal</h2>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-grid\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"nombre\">Nombre completo</label>\r\n");
      out.write("                                <div class=\"input-icon\">\r\n");
      out.write("                                    <svg class=\"icon\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                        <path d=\"M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2\"></path>\r\n");
      out.write("                                        <circle cx=\"12\" cy=\"7\" r=\"4\"></circle>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <input type=\"text\" id=\"nombre\" name=\"nombre\" placeholder=\"Tu nombre completo\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"email\">Correo electrónico</label>\r\n");
      out.write("                                <div class=\"input-icon\">\r\n");
      out.write("                                    <svg class=\"icon\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                        <path d=\"M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z\"></path>\r\n");
      out.write("                                        <polyline points=\"22,6 12,13 2,6\"></polyline>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"tu@email.com\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"password\">Contraseña</label>\r\n");
      out.write("                                <div class=\"input-icon\">\r\n");
      out.write("                                    <svg class=\"icon\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                        <rect x=\"3\" y=\"11\" width=\"18\" height=\"11\" rx=\"2\" ry=\"2\"></rect>\r\n");
      out.write("                                        <path d=\"M7 11V7a5 5 0 0 1 10 0v4\"></path>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Contraseña\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"confirm-password\">Confirmar contraseña</label>\r\n");
      out.write("                                <div class=\"input-icon\">\r\n");
      out.write("                                    <svg class=\"icon\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                        <rect x=\"3\" y=\"11\" width=\"18\" height=\"11\" rx=\"2\" ry=\"2\"></rect>\r\n");
      out.write("                                        <path d=\"M7 11V7a5 5 0 0 1 10 0v4\"></path>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <input type=\"password\" id=\"confirm-password\" name=\"confirmPassword\" placeholder=\"Confirmar contraseña\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-actions\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn primary\" onclick=\"showStep(2)\">Continuar</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"step-content hidden\" id=\"step2\">\r\n");
      out.write("                        <h2>Método de pago</h2>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"payment-tabs\">\r\n");
      out.write("                            <div class=\"tab-header\">\r\n");
      out.write("                                <button class=\"tab-btn active\" onclick=\"showTab('card')\">Tarjeta de crédito</button>\r\n");
      out.write("                                <button class=\"tab-btn\" onclick=\"showTab('paypal')\">PayPal</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"tab-content\" id=\"card-tab\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"card-name\">Nombre en la tarjeta</label>\r\n");
      out.write("                                    <input type=\"text\" id=\"card-name\" name=\"cardName\" placeholder=\"Nombre completo\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"card-number\">Número de tarjeta</label>\r\n");
      out.write("                                    <div class=\"input-icon\">\r\n");
      out.write("                                        <svg class=\"icon\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                                            <rect x=\"1\" y=\"4\" width=\"22\" height=\"16\" rx=\"2\" ry=\"2\"></rect>\r\n");
      out.write("                                            <line x1=\"1\" y1=\"10\" x2=\"23\" y2=\"10\"></line>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                        <input type=\"number\" id=\"card-number\" name=\"cardNumber\" placeholder=\"1234 5678 9012 3456\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"form-row\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"expiry\">Fecha de expiración</label>\r\n");
      out.write("                                        <input type=\"date\" id=\"expiry\" name=\"expiry\" placeholder=\"MM/AA\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label for=\"cvc\">CVC</label>\r\n");
      out.write("                                        <input type=\"number\" id=\"cvc\" name=\"cvc\" placeholder=\"123\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"tab-content hidden\" id=\"paypal-tab\">\r\n");
      out.write("                                <div class=\"paypal-content\">\r\n");
      out.write("                                    <p>Serás redirigido a PayPal para completar el pago.</p>\r\n");
      out.write("                                    <img src=\"paypal-logo.png\" alt=\"PayPal\" class=\"paypal-logo\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"order-summary\">\r\n");
      out.write("                            <h3>Resumen de tu suscripción</h3>\r\n");
      out.write("                            <div class=\"summary-row\">\r\n");
      out.write("                                <span>Suscripción</span>\r\n");
      out.write("                                <span>15,00$</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"summary-total\">\r\n");
      out.write("                                <span>Total</span>\r\n");
      out.write("                                <span>15,00$</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-actions\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn secondary\" onclick=\"showStep(1)\">Atrás</button>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn primary\">Completar suscripción</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>BilboSKP</h3>\r\n");
      out.write("                    <p>La mejor plataforma de escape rooms en Bilbao. Vive la aventura con nosotros.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>Enlaces</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"Index.jsp\">Inicio</a></li>\r\n");
      out.write("                        <li><a href=\"QuienesSomos.jsp\">Quiénes Somos</a></li>\r\n");
      out.write("                        <li><a href=\"EscapeRooms.jsp\">Salas de Escape</a></li>\r\n");
      out.write("                        <li><a href=\"Ayuda.jsp\">Ayuda</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-column\">\r\n");
      out.write("                    <h3>Contacto</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>Email: skpbilbo@gmail.com</li>\r\n");
      out.write("                        <li>Dirección: Calle Principal 123, Bilbao</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-bottom\">\r\n");
      out.write("                <p>&copy; 2025 BilboSKP. Todos los derechos reservados.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function showStep(stepNumber) {\r\n");
      out.write("            // Validación para el Paso 1 (Datos personales)\r\n");
      out.write("            if (stepNumber === 2) {\r\n");
      out.write("                const nombre = document.getElementById('nombre').value;\r\n");
      out.write("                const email = document.getElementById('email').value;\r\n");
      out.write("                const password = document.getElementById('password').value;\r\n");
      out.write("                const confirmPassword = document.getElementById('confirm-password').value;\r\n");
      out.write("\r\n");
      out.write("                if (nombre === '' || email === '' || password === '' || confirmPassword === '') {\r\n");
      out.write("                    alert('Por favor, completa todos los campos de información personal.');\r\n");
      out.write("                    return; // No avanzar al siguiente paso si hay campos vacíos\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if (password !== confirmPassword) {\r\n");
      out.write("                    alert('Las contraseñas no coinciden.');\r\n");
      out.write("                    return; // No avanzar si las contraseñas no coinciden\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Ocultar todos los contenidos de los pasos\r\n");
      out.write("            document.querySelectorAll('.step-content').forEach(step => {\r\n");
      out.write("                step.classList.add('hidden');\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Mostrar el contenido del paso seleccionado\r\n");
      out.write("            document.getElementById('step' + stepNumber).classList.remove('hidden');\r\n");
      out.write("\r\n");
      out.write("            // Actualizar la barra de progreso\r\n");
      out.write("            document.querySelectorAll('.step').forEach((step, index) => {\r\n");
      out.write("                if (index + 1 < stepNumber) {\r\n");
      out.write("                    step.classList.add('completed');\r\n");
      out.write("                    step.classList.add('active');\r\n");
      out.write("                } else if (index + 1 === stepNumber) {\r\n");
      out.write("                    step.classList.add('active');\r\n");
      out.write("                    step.classList.remove('completed');\r\n");
      out.write("                } else {\r\n");
      out.write("                    step.classList.remove('active');\r\n");
      out.write("                    step.classList.remove('completed');\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Actualizar las etiquetas de la barra de progreso\r\n");
      out.write("            document.querySelectorAll('.progress-labels span').forEach((label, index) => {\r\n");
      out.write("                if (index + 1 <= stepNumber) {\r\n");
      out.write("                    label.classList.add('active');\r\n");
      out.write("                } else {\r\n");
      out.write("                    label.classList.remove('active');\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function showTab(tabId) {\r\n");
      out.write("            // Ocultar todos los contenidos de las pestañas\r\n");
      out.write("            document.querySelectorAll('.tab-content').forEach(tab => {\r\n");
      out.write("                tab.classList.add('hidden');\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Mostrar el contenido de la pestaña seleccionada\r\n");
      out.write("            document.getElementById(tabId + '-tab').classList.remove('hidden');\r\n");
      out.write("\r\n");
      out.write("            // Actualizar los botones de las pestañas\r\n");
      out.write("            document.querySelectorAll('.tab-btn').forEach(btn => {\r\n");
      out.write("                btn.classList.remove('active');\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            event.target.classList.add('active');\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // La función submitForm ya no es necesaria con el formulario unificado\r\n");
      out.write("        // function submitForm() {\r\n");
      out.write("        //     // Validación para el Paso 2 (Método de pago - Tarjeta de crédito)\r\n");
      out.write("        //     const cardName = document.getElementById('card-name').value;\r\n");
      out.write("        //     const cardNumber = document.getElementById('card-number').value;\r\n");
      out.write("        //     const expiry = document.getElementById('expiry').value;\r\n");
      out.write("        //     const cvc = document.getElementById('cvc').value;\r\n");
      out.write("\r\n");
      out.write("        //     const cardTab = document.getElementById('card-tab');\r\n");
      out.write("        //     if (!cardTab.classList.contains('hidden')) { // Solo validar si la pestaña de tarjeta está visible\r\n");
      out.write("        //         if (cardName === '' || cardNumber === '' || expiry === '' || cvc === '') {\r\n");
      out.write("        //             alert('Por favor, completa todos los campos de la tarjeta de crédito.');\r\n");
      out.write("        //             return; // No mostrar el mensaje de éxito si faltan campos\r\n");
      out.write("        //         }\r\n");
      out.write("        //         // Aquí podrías añadir más validaciones para el formato de la tarjeta, fecha, etc.\r\n");
      out.write("        //     }\r\n");
      out.write("\r\n");
      out.write("        //     // Si llegamos aquí, significa que los campos requeridos (en el paso visible) están llenos\r\n");
      out.write("        //     alert('¡Suscripción completada con éxito!');\r\n");
      out.write("        //     // Aquí podrías añadir la lógica para enviar los datos del formulario al servidor\r\n");
      out.write("        // }\r\n");
      out.write("\r\n");
      out.write("        // Inicialmente mostrar solo el primer paso\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', () => {\r\n");
      out.write("            showStep(1);\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
