/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2025-04-27 18:09:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SolicitudEmail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/SolicitudEmail.css\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"logo-container\">\r\n");
      out.write("			<a href=\"Index.jsp\"><img\r\n");
      out.write("				src=\"img/bilboskp-high-resolution-logo-removebg-preview.png\"></a>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"language-selector\">\r\n");
      out.write("				<a href=\"?lang=es\" title=\"Español\"> <img\r\n");
      out.write("					src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/1200px-Flag_of_Spain.svg.png\"\r\n");
      out.write("					alt=\"Bandera de España\">\r\n");
      out.write("				</a> <a href=\"?lang=en\" title=\"English\"> <img\r\n");
      out.write("					src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg/1200px-Flag_of_the_United_Kingdom_%283-5%29.svg.png\"\r\n");
      out.write("					alt=\"Bandera del Reino Unido\">\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<nav>\r\n");
      out.write("\r\n");
      out.write("			<a href=\"EscapeRooms.jsp\">Jugar</a> <a href=\"OrganizarPartida.jsp\">Organizar\r\n");
      out.write("				Partida</a> <a href=\"Packcupones.jsp\">Comprar cupones</a> <a\r\n");
      out.write("				href=\"DevolverCupones.jsp\">Devolver cupones</a> <a\r\n");
      out.write("				href=\"QuienesSomos.jsp\">Quiénes Somos</a> <a href=\"Ayuda.jsp\">Ayuda</a>\r\n");
      out.write("\r\n");
      out.write("			");

			Integer idRolUsuario = (Integer) request.getAttribute("idRol");
			Integer idCentroSesion = (Integer) request.getAttribute("idCentroSesion");

			// Mostrar "Registrar Centro" solo si el usuario no está logueado como centro
			if (idCentroSesion == null && idRolUsuario != null && idRolUsuario.equals(2)) {
			
      out.write("\r\n");
      out.write("			<a href=\"CentroRegistro.jsp\">Registrar Centro</a>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</nav>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"botones\">\r\n");
      out.write("			");

			String nombreSesion = (String) request.getAttribute("nombreSesion");
			String tipoUsuario = (String) request.getAttribute("tipoUsuario");
			Integer saldoCupones = (Integer) request.getAttribute("saldoCupones");

			if (nombreSesion != null && !nombreSesion.isEmpty()) {
				if (tipoUsuario != null && tipoUsuario.equals("usuario")) {
			
      out.write("\r\n");
      out.write("			<span class=\"nombre-usuario\">Bienvenido, ");
      out.print(nombreSesion);
      out.write(' ');
      out.write('(');
      out.print(saldoCupones != null ? saldoCupones : 0);
      out.write("\r\n");
      out.write("				cupones)\r\n");
      out.write("			</span>\r\n");
      out.write("			<button onclick=\"window.location.href='LogoutServlet'\">Cerrar\r\n");
      out.write("				Sesión</button>\r\n");
      out.write("			");

			} else if (tipoUsuario != null && tipoUsuario.equals("centro")) {
			
      out.write("\r\n");
      out.write("			<span class=\"nombre-centro\">Bienvenido, ");
      out.print(nombreSesion);
      out.write("</span>\r\n");
      out.write("			<button onclick=\"window.location.href='LogoutCentroServlet'\">Cerrar\r\n");
      out.write("				Sesión</button>\r\n");
      out.write("			");

			}
			} else {
			
      out.write("\r\n");
      out.write("			<button class=\"registrarse\"\r\n");
      out.write("				onclick=\"window.location.href='Registrar.jsp'\">Registrarse</button>\r\n");
      out.write("			<button onclick=\"window.location.href='login.jsp'\">Iniciar\r\n");
      out.write("				Sesion</button>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<main>\r\n");
      out.write("		<div class=\"card\">\r\n");
      out.write("			<div class=\"card-header\">\r\n");
      out.write("				<div class=\"dots\">\r\n");
      out.write("					<span class=\"dot\"></span> <span class=\"dot\"></span> <span\r\n");
      out.write("						class=\"dot\"></span> <span class=\"dot\"></span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<a href=\"Registrar.jsp\" class=\"back-link\">\r\n");
      out.write("          <svg class=\"icon\" viewBox=\"0 0 24 24\">\r\n");
      out.write("            <line x1=\"19\" y1=\"12\" x2=\"5\" y2=\"12\"></line>\r\n");
      out.write("            <polyline points=\"12 19 5 12 12 5\"></polyline>\r\n");
      out.write("          </svg>\r\n");
      out.write("          Volver al menu\r\n");
      out.write("        </a>\r\n");
      out.write("				<h1 class=\"card-title\">Solicitud de Registro de Centro</h1>\r\n");
      out.write("				<p class=\"card-subtitle\">Sigue estas instrucciones para\r\n");
      out.write("					registrar tu centro educativo en BilboSKP</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"section\">\r\n");
      out.write("					<h2 class=\"section-title\">\r\n");
      out.write("						<svg class=\"icon\" viewBox=\"0 0 24 24\">\r\n");
      out.write("              <rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\" ry=\"2\"></rect>\r\n");
      out.write("              <line x1=\"16\" y1=\"2\" x2=\"16\" y2=\"6\"></line>\r\n");
      out.write("              <line x1=\"8\" y1=\"2\" x2=\"8\" y2=\"6\"></line>\r\n");
      out.write("              <line x1=\"3\" y1=\"10\" x2=\"21\" y2=\"10\"></line>\r\n");
      out.write("            </svg>\r\n");
      out.write("						Proceso de solicitud\r\n");
      out.write("					</h2>\r\n");
      out.write("					<div class=\"section-content\">\r\n");
      out.write("						<p>Para solicitar el registro de tu centro educativo en\r\n");
      out.write("							BilboSKP, debes enviar un correo electrónico con la información\r\n");
      out.write("							requerida siguiendo estos pasos:</p>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"steps\">\r\n");
      out.write("							<div class=\"step\">\r\n");
      out.write("								<div class=\"step-number\">1</div>\r\n");
      out.write("								<div class=\"step-content\">\r\n");
      out.write("									<strong>Dirección de correo:</strong> Envía tu solicitud a <strong>centros@bilboskp.com</strong>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"step\">\r\n");
      out.write("								<div class=\"step-number\">2</div>\r\n");
      out.write("								<div class=\"step-content\">\r\n");
      out.write("									<strong>Asunto del correo:</strong> \"Solicitud de registro de\r\n");
      out.write("									centro: [Nombre del centro]\"\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"step\">\r\n");
      out.write("								<div class=\"step-number\">3</div>\r\n");
      out.write("								<div class=\"step-content\">\r\n");
      out.write("									<strong>Contenido del correo:</strong> Incluye toda la\r\n");
      out.write("									información requerida según la plantilla que te proporcionamos\r\n");
      out.write("									a continuación.\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"step\">\r\n");
      out.write("								<div class=\"step-number\">4</div>\r\n");
      out.write("								<div class=\"step-content\">\r\n");
      out.write("									<strong>Espera la confirmación:</strong> Nuestro equipo\r\n");
      out.write("									revisará tu solicitud y te responderá en un plazo máximo de 48\r\n");
      out.write("									horas laborables.\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"section\">\r\n");
      out.write("					<h2 class=\"section-title\">\r\n");
      out.write("						<svg class=\"icon\" viewBox=\"0 0 24 24\">\r\n");
      out.write("              <path\r\n");
      out.write("								d=\"M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z\"></path>\r\n");
      out.write("              <polyline points=\"14 2 14 8 20 8\"></polyline>\r\n");
      out.write("              <line x1=\"16\" y1=\"13\" x2=\"8\" y2=\"13\"></line>\r\n");
      out.write("              <line x1=\"16\" y1=\"17\" x2=\"8\" y2=\"17\"></line>\r\n");
      out.write("              <polyline points=\"10 9 9 9 8 9\"></polyline>\r\n");
      out.write("            </svg>\r\n");
      out.write("						Plantilla para la solicitud\r\n");
      out.write("					</h2>\r\n");
      out.write("					<div class=\"section-content\">\r\n");
      out.write("						<p>Utiliza la siguiente plantilla para redactar tu correo\r\n");
      out.write("							electrónico de solicitud. Asegúrate de incluir toda la\r\n");
      out.write("							información requerida:</p>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"template\">\r\n");
      out.write("							Asunto: Solicitud de registro de centro: <span\r\n");
      out.write("								class=\"template-field\">[Nombre del centro]</span> Estimado\r\n");
      out.write("							equipo de BilboSKP, Me pongo en contacto con ustedes para\r\n");
      out.write("							solicitar el registro de nuestro centro educativo en su\r\n");
      out.write("							plataforma. A continuación, les proporciono la información\r\n");
      out.write("							requerida: <span class=\"template-field\">INFORMACIÓN DEL\r\n");
      out.write("								CENTRO:</span> - Nombre del centro: <span class=\"template-field\">[Nombre\r\n");
      out.write("								completo del centro educativo]</span> - Ubicación del centro: <span\r\n");
      out.write("								class=\"template-field\">[Dirección completa, incluyendo\r\n");
      out.write("								ciudad y código postal]</span> - Número de alumnos: <span\r\n");
      out.write("								class=\"template-field\">[Número total de alumnos\r\n");
      out.write("								matriculados]</span> <span class=\"template-field\">INFORMACIÓN\r\n");
      out.write("								DEL SOLICITANTE:</span> - Nombre del solicitante: <span\r\n");
      out.write("								class=\"template-field\">[Tu nombre completo]</span> - Puesto que\r\n");
      out.write("							ocupa en el centro: <span class=\"template-field\">[Tu cargo\r\n");
      out.write("								o función en el centro educativo]</span> - Correo electrónico de\r\n");
      out.write("							contacto: <span class=\"template-field\">[Tu correo\r\n");
      out.write("								electrónico profesional]</span> - Teléfono de contacto: <span\r\n");
      out.write("								class=\"template-field\">[Tu número de teléfono]</span> Quedo a la\r\n");
      out.write("							espera de su respuesta y disponible para proporcionar cualquier\r\n");
      out.write("							información adicional que puedan necesitar. Atentamente, <span\r\n");
      out.write("								class=\"template-field\">[Tu nombre]</span> <span\r\n");
      out.write("								class=\"template-field\">[Tu cargo]</span> <span\r\n");
      out.write("								class=\"template-field\">[Nombre del centro]</span>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"info-box\">\r\n");
      out.write("							<div class=\"info-box-title\">\r\n");
      out.write("								<svg class=\"icon\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                  <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\r\n");
      out.write("                  <line x1=\"12\" y1=\"16\" x2=\"12\" y2=\"12\"></line>\r\n");
      out.write("                  <line x1=\"12\" y1=\"8\" x2=\"12.01\" y2=\"8\"></line>\r\n");
      out.write("                </svg>\r\n");
      out.write("								Información importante\r\n");
      out.write("							</div>\r\n");
      out.write("							<p>Todos los campos marcados en azul son obligatorios. La\r\n");
      out.write("								solicitud no podrá ser procesada si falta alguno de estos datos.\r\n");
      out.write("								Asegúrate de utilizar un correo electrónico institucional para\r\n");
      out.write("								mayor credibilidad.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"section\">\r\n");
      out.write("					<h2 class=\"section-title\">\r\n");
      out.write("						<svg class=\"icon\" viewBox=\"0 0 24 24\">\r\n");
      out.write("              <path d=\"M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z\"></path>\r\n");
      out.write("            </svg>\r\n");
      out.write("						Verificación y aprobación\r\n");
      out.write("					</h2>\r\n");
      out.write("					<div class=\"section-content\">\r\n");
      out.write("						<p>Una vez recibida tu solicitud, nuestro equipo verificará la\r\n");
      out.write("							información proporcionada. Es posible que nos pongamos en\r\n");
      out.write("							contacto contigo para solicitar documentación adicional que\r\n");
      out.write("							acredite la existencia del centro educativo.</p>\r\n");
      out.write("						<p>Tras la verificación, recibirás un correo electrónico con\r\n");
      out.write("							las credenciales de acceso a la plataforma y las instrucciones\r\n");
      out.write("							para completar la configuración de tu cuenta de centro.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"button-container\">\r\n");
      out.write("					<a href=\"mailto:centros@bilboskp.com\" class=\"primary-button\"> <svg\r\n");
      out.write("							class=\"icon\" viewBox=\"0 0 24 24\">\r\n");
      out.write("              <path\r\n");
      out.write("								d=\"M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z\"></path>\r\n");
      out.write("              <polyline points=\"22,6 12,13 2,6\"></polyline>\r\n");
      out.write("            </svg> Enviar solicitud por correo\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"footer-content\">\r\n");
      out.write("				<div class=\"footer-column\">\r\n");
      out.write("					<h3>BilboSKP</h3>\r\n");
      out.write("					<p>La mejor plataforma de escape rooms en Bilbao. Vive la\r\n");
      out.write("						aventura con nosotros.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"footer-column\">\r\n");
      out.write("					<h3>Enlaces</h3>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"Index.jsp\">Inicio</a></li>\r\n");
      out.write("						<li><a href=\"QuienesSomos.jsp\">Quiénes Somos</a></li>\r\n");
      out.write("						<li><a href=\"EscapeRooms.jsp\">Salas de Escape</a></li>\r\n");
      out.write("						<li><a href=\"Ayuda.jsp\">Ayuda</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"footer-column\">\r\n");
      out.write("					<h3>Contacto</h3>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li>Email: skpbilbo@gmail.com</li>\r\n");
      out.write("						<li>Dirección: Calle Principal 123, Bilbao</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"footer-bottom\">\r\n");
      out.write("				<p>&copy; 2025 BilboSKP. Todos los derechos reservados.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		// Script para copiar la plantilla al portapapeles\r\n");
      out.write("		document.querySelector('.template').addEventListener('click',\r\n");
      out.write("				function() {\r\n");
      out.write("					const el = document.createElement('textarea');\r\n");
      out.write("					el.value = this.textContent.trim();\r\n");
      out.write("					document.body.appendChild(el);\r\n");
      out.write("					el.select();\r\n");
      out.write("					document.execCommand('copy');\r\n");
      out.write("					document.body.removeChild(el);\r\n");
      out.write("\r\n");
      out.write("					alert('Plantilla copiada al portapapeles');\r\n");
      out.write("				});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
